version: 1
builder:
  configs:
    - documentation_targets:
        - SwiftHelpers
      platform: ios
    - documentation_targets:
        - SwiftHelpers
      platform: macosSpm
    - documentation_targets:
        - SwiftHelpers
      platform: macosXcodebuild
